### ISSUE TITLE
Few errors with http://md5hashing.net

### ISSUE THREAD

**Issue by Ashtor** [FVetrov/md5hashing.net#10]
Here are the errors:
1. On http://md5hashing.net/open/chat#main and I tried to chat and suddenly i saw the message "An error occurred,please try refresh page or re-login again",, I did what it said by refresh the page and relogin again,but still i got that message. And I got the error "Fatal error: Out of memory (allocated 2883584) (tried to allocate 12288 bytes) in /var/www/md5hashing/laravel/session.php on line 79"

2.  I was on http://md5hashing.net/anonymous/email#main and i got this when I clicked that link: "Error: Fatal error: Out of memory (allocated 2883584) (tried to allocate 12288 bytes) in /var/www/md5hashing/laravel/session.php on line 79" and second issue with it,is that i tested by sending a email to a created emailaddress i got from that link and i refreshed the email inbox there and nothing came.

In fact there are other places that get that error. Can't mention all since there are more,but check the site [including the main site md5hashing.net i get "Fatal error: Out of memory (allocated 2883584) (tried to allocate 12288 bytes) in /var/www/md5hashing/laravel/session.php on line 79"]

Once you fixed it,let me know

**Comment by FVetrov** [comment]
Thank you for report - all fixed now
