### ISSUE TITLE
Site problem

### ISSUE THREAD

**Issue by Ashtor** [FVetrov/md5hashing.net#12]
Instead of explain the problem,i show you a photo of the problem instead.. here it is: http://i.imgur.com/zTL0N73.png

(if that link doesn't work whenever you get the chance to check the link,i repost the issue if the error on the site still exist)

**Comment by FVetrov** [comment]
Thank you for report, somewhy mogodb goes down, to this issue was applied temporary fix. 
Investigating the source of problem

**Comment by FVetrov** [comment]
fixed
