### ISSUE TITLE
Can't enter http://md5hashing.net

### ISSUE THREAD

**Issue by Ashtor** [FVetrov/md5hashing.net#13]
Hi
Hard to explain the issue here. just saying that I can't enter the site. here is a photo of it that explain it easier: http://i.imgur.com/0DiTcZt.png

**Comment by FVetrov** [comment]
@Ashtor md5hashing.net was blocked in some areas and countries, from where are you trying to connect? To solve - try use any proxy or tor.

**Comment by Ashtor** [comment]
i never used tor or proxy when using the site and I have used the site on opera browser and chrome without any problem,but now I can't. if you asking me from what country i'm connecting from,its Norway
