### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by mamirsoleimani** [FVetrov/md5hashing.net#16]

**Comment by mamirsoleimani** [comment]
Dear friends
How I can I identify the following string algorithm:

JOJKLNSPRSGSTUVYXYZ0123456B89ABCDEFGHIJKLMNOPQRSTUVWUVWXGHIJKLMNECJCOMLG835


Please help me

**Comment by mamirsoleimani** [comment]
Dear friends
How I can I identify the following string algorithm:

JOJKLNSPRSGSTUVYXYZ0123456B89ABCDEFGHIJKLMNOPQRSTUVWUVWXGHIJKLMNECJCOMLG835

Please help me

**Comment by jigas** [comment]
on VideoMega.tv http://videomega.tv/?ref=AJWOLaJQKbbKQJaLOWJA

the url : AJWOLaJQKbbKQJaLOWJA converts to 065074087079076097074081075098098075081074097076079087074065

when getting embed code.
how can i convert the numbers to the original hash?

**Comment by FVetrov** [comment]
@jigas @mamirsoleimani  Can we close this? If not, just reopen an issue.
