### ISSUE TITLE
Website name is not correct when adblock alert message is displayed

### ISSUE THREAD

**Issue by gulshansainis** [FVetrov/md5hashing.net#23]
Steps to reproduce
1. Enable adblock on browser
2. Navigate to https://md5hashing.net
3. Observe adblock message 

_please disable AdBlocker for md5hadhing.net domain._

Issue: The website does not match domain name
<img width="466" alt="screen shot 2016-03-21 at 9 46 17 am" src="https://cloud.githubusercontent.com/assets/8197984/13910538/caa20054-ef49-11e5-81c8-43b1c149aa1c.png">

**Comment by FVetrov** [comment]
@gulshansainis thank you. It was fixed a while ago.
