### ISSUE TITLE
Request deletion

### ISSUE THREAD

**Issue by TheDrifter363-zz** [FVetrov/md5hashing.net#26]
Hey,

Sorry I may have posted personal information on your website. I did not realize how it worked and I apologize for my transgression. Is there any way I can request its removal? I attempted to fill out the removal form on your website, md5hashing.net, but I kept receiving a recaptcha error. Please let me know what I can do. Thank you.

**Comment by FVetrov** [comment]
Hi @TheDrifter363 ,

Thank you for reaching us.
Yes, we just confirmed an error with filling abuse form.
You can send an email directly to us with a link where data is posted and a reason why this should be removed.

**Comment by FVetrov** [comment]
Solved.
