### ISSUE TITLE
Request on removing "Last Queries List"

### ISSUE THREAD

**Issue by Ashtor** [FVetrov/md5hashing.net#9]
I did uncheck and checked the "Save result to DB",but still it comes to "Last Queries List". Best way to avoid it is to remove the listing and "Last Queries List" from the site completely. there was the same issue posted for like 10 months ago.. please remove the "Last Queries List" from the site. There is another issue I want to tell. The anonymous email. The email i tried to send as a test,didnt come to the email at all. A question: What is the enail to send to the owners if md5hashing.net ?

**Comment by Ashtor** [comment]
It wont be called encryption and/or encrypted if that "Last Queries List" is there,so please remove it

**Comment by FVetrov** [comment]
@Ashtor our website mainly do the reverse decryption
If you don't like it - do not use it, please.

> I did uncheck and checked the "Save result to DB",but still it comes to "Last Queries List".

Checked, - worked as expected,
